Configuring for pure-python-without-pypy
zopefoundation/zLOG pull request #4
Opened 2020-02-14 15:39 UTC by icemac

2020-02-14 15:50 UTC, icemac commented
The script does not support updating an existing PR, so the changes in .gitignore could be done manually or in another PR.

2020-02-14 15:51 UTC, dataflake commented
That's the reason why I want to discuss that before you apply it anywhere...

2020-02-14 15:55 UTC, dataflake requested changes

2020-02-14 15:55 UTC, dataflake commented on .gitignore
> +parts/
Missing:

- pyvenv.cfg
- /lib64
- *.profraw

2020-02-14 15:55 UTC, dataflake commented on tox.ini
> +[coverage:run]
Question I asked on zopefoundation/meta#12: Does this configuration get picked up correctly when it's here and not in setup.cfg?

2020-02-17 15:30 UTC, closed without merging

2020-02-17 16:14 UTC, icemac commented
Replaced by #5 which includes the requested changes.